version: 0.2

env:
  shell: bash
    
phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm install
      - CI=true npm run test
      - |
        API_ROOT=`aws ssm get-parameter --name "/${AWS_DEFAULT_REGION}/${STAGE,,}/ApiGwEndpoint" --region "${AWS_DEFAULT_REGION}" --query 'Parameter.Value' --output text`
        sed -i "s|https://conduit.productionready.io/api|${API_ROOT}/api|g" src/agent.js
  build:
    commands:
      - echo Entered the build phase...
      - echo Building the Website package...
      - npm run build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo $S3_BUCKET_NAME
      - aws s3 sync build/ s3://$S3_BUCKET_NAME
