version: 0.2

env:
  shell: bash
  parameter-store:
    key: "value"

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm install
      - CI=true npm run test
  build:
    commands:
      - echo Entered the build phase...
      - echo Building the Website package...
      - npm run build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - aws s3 sync build/ s3://$S3_BUCKET_NAME
